name: Q&A template
description: File a Q&A for peer review
title: "[Q&A]: "
labels: ["Q&A", "Needs peer review","Needs approval"]
assignees:
 - joaoxg
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute with you Q&A!
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Introduce the question with which you intend to contribute for the model fine tunning
    validations:
      required: true
  - type: textarea
    id: answer
    attributes:
      label: Answer
      description: Introduce the respective answer with which you intend to contribute for the model fine tunning
    validations:
      required: true
  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: To which of the following topics does the Q&A refer?
      options:
        - Topic A
        - Topic B
    validations:
      required: true
  - type: dropdown
    id: references
    attributes:
      label: To which of the following topics does the Q&A refer?
      options:
        - Reference 1
        - Reference 2
        - Reference 3